# Generated by Django 4.1.7 on 2023-02-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hbm", "0003_remove_transaction_transaction_balance_now"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_balance_now",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
