# Generated by Django 4.1.7 on 2023-02-23 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hbm", "0004_transaction_transaction_balance_now"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction", name="transaction_balance_now",
        ),
    ]
